CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    URL_PHOTO VARCHAR(128)
);

CREATE TABLE KUDOS_CONVERSION (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(10),
    POINTS INTEGER,
    REWARD NUMERIC(20,2)
);

CREATE TABLE KUDOS_ENTRY (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_USER_GIVEN INTEGER REFERENCES USERS (ID),
    ID_USER_RECEIVED INTEGER REFERENCES USERS (ID),
    DATE_TIME TIMESTAMP,
    POINTS INTEGER,
    REWARD NUMERIC(20,2)
);

CREATE TABLE KUDOS_ENTRY_DETAIL (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_KUDOS_ENTRY INTEGER REFERENCES KUDOS_ENTRY (ID),
    ID_KUDOS_CONVERSION INTEGER REFERENCES KUDOS_CONVERSION (ID),
    POINTS INTEGER,
    REWARD NUMERIC(20,2)
);
